name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    uses: ./.github/workflows/common.yml
    with:
      python-version: '3.7'
      os: ubuntu-20.04
      make-packages: false
